part of 'main.dart';

class Today extends StatelessWidget {
  const Today({super.key});
  @override Widget build(BuildContext c) => page([
    Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [sub('9月9日 · 星期三'), const SizedBox(height: 3), title('晚上好，Alex')])),
      InkWell(borderRadius: BorderRadius.circular(24), onTap: () => push(c, const Profile()), child: const CircleAvatar(radius: 19, backgroundColor: C.ps, child: Icon(Icons.person, color: C.p, size: 20))),
    ]),
    const SizedBox(height: 12), const _Week(), const SizedBox(height: 11),
    panel(Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      const Text('TODAY FOCUS', style: TextStyle(fontSize: 9.5, fontWeight: FontWeight.w900, color: C.p)), const SizedBox(height: 8),
      const Row(children: [Icon(Icons.favorite_rounded, size: 14, color: C.red), SizedBox(width: 7), Expanded(child: Text('完成论文实验设计', style: TextStyle(fontSize: 14, fontWeight: FontWeight.w900)))]),
      const Padding(padding: EdgeInsets.only(left: 21, top: 3), child: Text('♙ Academic Research', style: TextStyle(fontSize: 9.5, color: C.muted))),
      const Padding(padding: EdgeInsets.only(left: 21, top: 3), child: Text('今天 23:00  ·  高优先级', style: TextStyle(fontSize: 9.5, color: C.muted))),
      const SizedBox(height: 10), SizedBox(width: double.infinity, child: FilledButton.icon(onPressed: () => push(c, const Focus()), icon: const Icon(Icons.play_arrow_rounded, size: 17), label: const Text('开始专注', style: TextStyle(fontSize: 11, fontWeight: FontWeight.w800))))
    ]), color: C.ps),
    h('今天'), const _InlineStats(),
    h('现在'), _TimeItem('19:00', '健身', '胸 + 三头', active: true, tap: () => push(c, const TaskDetail())),
    h('接下来'), _TimeItem('21:00', '修改实验代码', '', tap: () => push(c, const TaskDetail())), _TimeItem('22:30', '英语学习', '', tap: () => push(c, const TaskDetail())),
    h('任务', tail: const Text('2项', style: TextStyle(fontSize: 9, color: C.muted))),
    _TaskLine('修复 MPC 仿真', 'Academic · 今天', tap: () => push(c, const TaskDetail())),
    _TaskLine('完成周报', '工作 · 明天', tap: () => push(c, const TaskDetail())),
  ]);
}

class _Week extends StatelessWidget { const _Week(); @override Widget build(BuildContext c) { const ds=['7','8','9','10','11','12','13']; const ws=['一','二','三','四','五','六','日']; return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: List.generate(7,(i){final s=i==2; return SizedBox(width:37, child: Column(children:[Text(ws[i],style:const TextStyle(fontSize:8,color:C.muted)),const SizedBox(height:4),Container(width:29,height:29,alignment:Alignment.center,decoration:BoxDecoration(color:s?C.p:Colors.transparent,borderRadius:BorderRadius.circular(9)),child:Text(ds[i],style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:s?Colors.white:C.ink)))]));})); } }
class _InlineStats extends StatelessWidget { const _InlineStats(); @override Widget build(BuildContext c)=>const Padding(padding:EdgeInsets.symmetric(vertical:3),child:Row(children:[Text('5',style:TextStyle(color:C.p,fontWeight:FontWeight.w900,fontSize:15)),Text(' 待完成  ·  ',style:TextStyle(fontSize:10,color:C.muted)),Text('2',style:TextStyle(color:C.p,fontWeight:FontWeight.w900,fontSize:15)),Text(' 日程  ·  ',style:TextStyle(fontSize:10,color:C.muted)),Text('1',style:TextStyle(color:C.p,fontWeight:FontWeight.w900,fontSize:15)),Text(' 习惯',style:TextStyle(fontSize:10,color:C.muted))])); }
class _TimeItem extends StatelessWidget { const _TimeItem(this.time,this.name,this.meta,{this.active=false,this.tap}); final String time,name,meta; final bool active; final VoidCallback? tap; @override Widget build(BuildContext c)=>InkWell(onTap:tap,child:Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:45,child:Text(time,style:const TextStyle(fontSize:10,color:C.muted))),Container(width:7,height:7,margin:const EdgeInsets.only(top:4),decoration:BoxDecoration(shape:BoxShape.circle,color:active?C.p:Colors.white,border:Border.all(color:active?C.p:C.muted))),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontSize:11.5,fontWeight:FontWeight.w800)),if(meta.isNotEmpty)Text(meta,style:const TextStyle(fontSize:9.5,color:C.muted))])),if(active)chip('进行中',bg:const Color(0xffe8f8ef),fg:C.green)]))); }
class _TaskLine extends StatelessWidget { const _TaskLine(this.name,this.meta,{this.tap}); final String name,meta; final VoidCallback? tap; @override Widget build(BuildContext c)=>InkWell(onTap:tap,child:Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[const Icon(Icons.circle_outlined,size:17,color:C.muted),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontSize:11.5,fontWeight:FontWeight.w800)),Text(meta,style:const TextStyle(fontSize:9.5,color:C.muted))]))]))); }

class Tasks extends StatefulWidget { const Tasks({super.key}); @override State<Tasks> createState()=>_TasksState(); }
class _TasksState extends State<Tasks> { int f=0; @override Widget build(BuildContext c)=>Scaffold(backgroundColor:C.bg,floatingActionButton:FloatingActionButton.small(backgroundColor:C.p,foregroundColor:Colors.white,onPressed:()=>_composer(c),child:const Icon(Icons.add)),body:page([
  Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[title('任务'),sub('管理你需要完成的事情')])),IconButton(onPressed:(){},icon:const Icon(Icons.tune_rounded,size:18))]),
  const SizedBox(height:10),const TextField(decoration:InputDecoration(hintText:'搜索任务...',prefixIcon:Icon(Icons.search_rounded,size:18))),const SizedBox(height:9),
  _Tabs(labels:const ['全部','今天','即将到期','等待中'],selected:f,onTap:(v)=>setState(()=>f=v)),
  h('今天 · 3'),panel(Column(children:[_TaskRow('完成论文 Experiment 1','Academic · 今天 22:00','P1',C.red,()=>push(c,const TaskDetail())),const Divider(height:1),_TaskRow('修改 LifeTrace API','LifeTrace · 今天','P2',C.orange,()=>push(c,const TaskDetail())),const Divider(height:1),_TaskRow('健身','Personal · 今天 19:00','',C.muted,()=>push(c,const TaskDetail()))])),
  h('明天 · 2'),panel(Column(children:[_TaskRow('完成周报','工作','','',()=>push(c,const TaskDetail())),const Divider(height:1),_TaskRow('阅读论文','Academic','','',()=>push(c,const TaskDetail()))])),
  h('接下来 · 4'),panel(Column(children:[_TaskRow('优化算法代码','9月12日','','',()=>push(c,const TaskDetail())),const Divider(height:1),_TaskRow('整理会议记录','工作','','',()=>push(c,const TaskDetail()))])),
]));
  Future<void> _composer(BuildContext c)=>showModalBottomSheet(context:c,isScrollControlled:true,showDragHandle:true,builder:(x)=>Padding(padding:EdgeInsets.fromLTRB(16,0,16,20+MediaQuery.of(x).viewInsets.bottom),child:Column(mainAxisSize:MainAxisSize.min,children:[const TextField(autofocus:true,decoration:InputDecoration(hintText:'任务标题')),const SizedBox(height:10),const TextField(maxLines:3,decoration:InputDecoration(hintText:'描述')),const SizedBox(height:12),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(x),child:const Text('保存任务')))])));
}
class _Tabs extends StatelessWidget { const _Tabs({required this.labels,required this.selected,required this.onTap}); final List<String> labels; final int selected; final ValueChanged<int> onTap; @override Widget build(BuildContext c)=>SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:List.generate(labels.length,(i)=>Padding(padding:const EdgeInsets.only(right:7),child:InkWell(onTap:()=>onTap(i),borderRadius:BorderRadius.circular(8),child:chip(labels[i],bg:i==selected?C.ps:C.soft,fg:i==selected?C.p:C.muted)))))); }
class _TaskRow extends StatelessWidget { const _TaskRow(this.name,this.meta,this.badge,this.color,this.tap); final String name,meta,badge; final dynamic color; final VoidCallback tap; @override Widget build(BuildContext c)=>InkWell(onTap:tap,child:Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Row(children:[const Icon(Icons.circle_outlined,size:17,color:C.muted),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontSize:11.5,fontWeight:FontWeight.w800)),Text(meta,style:const TextStyle(fontSize:9.2,color:C.muted))])),if(badge.isNotEmpty)chip(badge,bg:(color as Color).withValues(alpha:.12),fg:color)]))); }

class TaskDetail extends StatefulWidget { const TaskDetail({super.key}); @override State<TaskDetail> createState()=>_TaskDetailState(); }
class _TaskDetailState extends State<TaskDetail>{ bool a=true,b=false,c2=false; @override Widget build(BuildContext c)=>DetailFrame(titleText:'',actions:const [Icon(Icons.more_vert_rounded,size:19)],child:page([
  Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:20,height:20,decoration:BoxDecoration(border:Border.all(color:C.p,width:1.5),borderRadius:BorderRadius.circular(5))),const SizedBox(width:9),Expanded(child:Text('完成 LifeTrace Execute UI',style:Theme.of(c).textTheme.titleLarge))]),
  const SizedBox(height:8),Wrap(spacing:5,children:[chip('P1',bg:const Color(0xffffe9e9),fg:C.red),chip('LifeTrace',bg:C.ps,fg:C.p),chip('进行中',bg:const Color(0xffe8f8ef),fg:C.green)]),
  h('描述'),const Text('重新整理 Android Execute 客户端界面，使用 Jetpack Compose 和 Material 3，提升整体体验。',style:TextStyle(fontSize:10.5,color:C.muted)),
  h('属性'),panel(const Column(children:[_Prop(Icons.schedule_rounded,'时间','9月10日 20:00'),Divider(height:1),_Prop(Icons.priority_high_rounded,'优先级','高'),Divider(height:1),_Prop(Icons.folder_outlined,'项目','LifeTrace Execute'),Divider(height:1),_Prop(Icons.notifications_none_rounded,'提醒','提前 30 分钟'),Divider(height:1),_Prop(Icons.repeat_rounded,'重复','不重复')])),
  h('子任务   1/3'),panel(Column(children:[CheckboxListTile(dense:true,contentPadding:EdgeInsets.zero,value:a,title:const Text('分析现有页面',style:TextStyle(fontSize:11)),onChanged:(v)=>setState(()=>a=v??false)),const Divider(height:1),CheckboxListTile(dense:true,contentPadding:EdgeInsets.zero,value:b,title:const Text('完成 UI Design',style:TextStyle(fontSize:11)),onChanged:(v)=>setState(()=>b=v??false)),const Divider(height:1),CheckboxListTile(dense:true,contentPadding:EdgeInsets.zero,value:c2,title:const Text('Compose 实现',style:TextStyle(fontSize:11)),onChanged:(v)=>setState(()=>c2=v??false)),const Align(alignment:Alignment.centerLeft,child:Padding(padding:EdgeInsets.only(top:4),child:Text('+  添加子任务',style:TextStyle(fontSize:10,color:C.p,fontWeight:FontWeight.w700))))])),
  h('关联内容'),Row(children:[Expanded(child:panel(const Row(children:[Icon(Icons.note_alt_outlined,size:15,color:C.p),SizedBox(width:5),Text('2 条笔记',style:TextStyle(fontSize:9.5))]),padding:const EdgeInsets.all(9))),const SizedBox(width:6),Expanded(child:panel(const Row(children:[Icon(Icons.insert_drive_file_outlined,size:15,color:C.p),SizedBox(width:5),Text('1 个文件',style:TextStyle(fontSize:9.5))]),padding:const EdgeInsets.all(9))),const SizedBox(width:6),Expanded(child:panel(const Row(children:[Icon(Icons.link,size:15,color:C.p),SizedBox(width:5),Text('1 个链接',style:TextStyle(fontSize:9.5))]),padding:const EdgeInsets.all(9)))]),
  const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>push(c,const Focus()),icon:const Icon(Icons.play_arrow_rounded,size:17),label:const Text('开始专注')))
],padding:const EdgeInsets.fromLTRB(14,4,14,18)));
}
class _Prop extends StatelessWidget { const _Prop(this.icon,this.label,this.value); final IconData icon; final String label,value; @override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Row(children:[Icon(icon,size:15,color:C.muted),const SizedBox(width:8),Text(label,style:const TextStyle(fontSize:10,color:C.muted)),const Spacer(),Text(value,style:const TextStyle(fontSize:10.5,fontWeight:FontWeight.w700)),const SizedBox(width:4),const Icon(Icons.chevron_right_rounded,size:15,color:C.muted)])); }
